import pandas as pd
import requests
import time
import json
import os

# Configuration
INPUT_FILE = os.path.join(os.path.dirname(__file__), '【航旅纵横】 行程导出.xls')
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), '..', 'data')
OUTPUT_FILE = os.path.join(OUTPUT_DIR, 'flights.js')
CACHE_FILE = os.path.join(os.path.dirname(__file__), 'airport_gps.json')

# Nominatim API
def geocode_city(city_name, cache):
    # Check cache first
    if city_name in cache:
        return cache[city_name]
    
    print(f"Geocoding {city_name}...")
    
    # Determine queries to try
    queries = []
    
    # 1. Try with "Airport" suffix (Chinese)
    queries.append(f"{city_name}机场")
    
    # 2. Fallback to original name (City center is better than nothing)
    queries.append(city_name)
    
    url = "https://nominatim.openstreetmap.org/search"
    headers = {'User-Agent': 'MyTravelMap/1.0 (flight-path-tracker)'}
    
    for query in queries:
        try:
            # print(f"  Trying query: {query}") 
            params = {'q': query, 'format': 'json', 'limit': 1}
            response = requests.get(url, params=params, headers=headers, timeout=10)
            response.raise_for_status()
            data = response.json()
            
            if data:
                result = {
                    'lat': float(data[0]['lat']),
                    'lon': float(data[0]['lon'])
                }
                cache[city_name] = result
                time.sleep(1.1) # Respect rate limit
                print(f"  Found: {query}")
                return result
            
            time.sleep(1.1) # Respect rate limit even on failure to avoid hammering
            
        except Exception as e:
            print(f"  Error querying {query}: {e}")
            continue

    print(f"Could not geocode {city_name} after trying: {queries}")
    return None

def main():
    # Load Cache
    city_cache = {}
    if os.path.exists(CACHE_FILE):
        with open(CACHE_FILE, 'r', encoding='utf-8') as f:
            city_cache = json.load(f)

    # Read Excel (All Sheets)
    try:
        # sheet_name=None reads all sheets as a dict of DataFrames
        all_sheets = pd.read_excel(INPUT_FILE, sheet_name=None)
        df_list = []
        for sheet_name, sheet_df in all_sheets.items():
            print(f"Processing sheet: {sheet_name} with {len(sheet_df)} rows")
            df_list.append(sheet_df)
        
        if df_list:
            df = pd.concat(df_list, ignore_index=True)
            print(f"Total rows after merging: {len(df)}")
        else:
            print("No data found in any sheet.")
            return

    except Exception as e:
        print(f"Error reading Excel file: {e}")
        return

    flights = []
    
    # Iterate through rows
    # Expected columns: 日期, 航空公司, 航班号, 出发城市, 出发时间, 到达城市, 到达时间
    # Map to: date, airline, flight_no, dep_city, dep_time, arr_city, arr_time
    
    for index, row in df.iterrows():
        try:
            dep_city = row['出发城市']
            arr_city = row['到达城市']
            
            # Geocode
            dep_coords = geocode_city(dep_city, city_cache)
            arr_coords = geocode_city(arr_city, city_cache)
            
            if dep_coords and arr_coords:
                flight = {
                    'date': str(row['日期']), # Convert timestamp/datetime to string
                    'airline': row['航空公司'],
                    'flight_no': row['航班号'],
                    'dep_city': dep_city,
                    'dep_time': str(row['出发时间']),
                    'arr_city': arr_city,
                    'arr_time': str(row['到达时间']),
                    'from_lat': dep_coords['lat'],
                    'from_lon': dep_coords['lon'],
                    'to_lat': arr_coords['lat'],
                    'to_lon': arr_coords['lon']
                }
                flights.append(flight)
        except Exception as e:
            print(f"Error processing row {index}: {e}")
            continue

    # Save Cache
    with open(CACHE_FILE, 'w', encoding='utf-8') as f:
        json.dump(city_cache, f, indent=2, ensure_ascii=False)

    # Save Flight Data
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    json_string = json.dumps(flights, indent=2, ensure_ascii=False)
    file_content = f"// Generated by parse_flights.py\nconst myFlights = {json_string};"
    
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(file_content)
        
    print(f"Successfully processed {len(flights)} flights. Saved to {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
